In [3]:
#DFS

import time
import sys

state_dict = {}

def move_left(state):
    new_state = state[:]
    index = new_state.index(0)
    if index not in [0, 3, 6]:
        new_state[index], new_state[index - 1] = new_state[index - 1], new_state[index]
        return new_state
    else:
        return None

def move_down(state):
    new_state = state[:]
    index = new_state.index(0)
    if index not in [6, 7, 8]:
        new_state[index], new_state[index + 3] = new_state[index + 3], new_state[index]
        return new_state
    else:
        return None

def move_up(state):
    new_state = state[:]
    index = new_state.index(0)
    if index not in [0, 1, 2]:
        new_state[index], new_state[index - 3] = new_state[index - 3], new_state[index]
        return new_state
    else:
        return None

def move_right(state):
    new_state = state[:]
    index = new_state.index(0)
    if index not in [2, 5, 8]:
        new_state[index], new_state[index + 1] = new_state[index + 1], new_state[index]
        return new_state
    else:
        return None


def create_node(state, parent, operator, depth, cost):
    return Node(state, parent, operator, depth, cost)


def expand_node(node, nodes):
    expanded_nodes = []
    expanded_nodes.append(create_node(move_up(node.state), node, "Up", node.depth + 1, 0))
    expanded_nodes.append(create_node(move_down(node.state), node, "Down", node.depth + 1, 0))
    expanded_nodes.append(create_node(move_left(node.state), node, "Left", node.depth + 1, 0))
    expanded_nodes.append(create_node(move_right(node.state), node, "Right", node.depth + 1, 0))
    expanded_nodes = [node for node in expanded_nodes if node.state is not None]
    return expanded_nodes

class Node:
    def __init__(self, state, parent, operator, depth, cost):
        self.state = state
        self.parent = parent
        self.operator = operator
        self.depth = depth
        self.cost = cost

def dfs(start,goal):
    nodes = []
    visited = []
    depth_limit = 1000
    nodes.append(create_node(start, None, None, 0, 0))
    start_time = time.time()
    while len(nodes) > 0:
        elapsed_time = time.time() - start_time
        if (elapsed_time < 80):
            if len(nodes) == 0: return None
            node = nodes.pop(0)
            state_str = "".join(str(n) for n in node.state)
            if state_str in state_dict:
                continue
            state_dict[state_str] = True
            visited.append(node)
            print(node.state)
            if node.state == goal:
                moves = []
                temp = node
                print(temp.depth)
                while True:
                    moves.insert(0, temp.operator)
                    if temp.depth <= 1: break
                    temp = temp.parent
                return moves
            if node.depth < depth_limit:
                expanded_nodes = expand_node(node, nodes)
                if(expanded_nodes not in visited):
                    expanded_nodes.extend(nodes)
                    nodes = expanded_nodes
        else:
            return None

        
if __name__ == "__main__":
    goal_state = [1,2,3,4,5,6,7,8,0]
    init_state = [1,2,3,0,4,6,7,5,8]
    dfs(init_state,goal_state)

0.0
[1, 2, 3, 0, 4, 6, 7, 5, 8]
0.0
[0, 2, 3, 1, 4, 6, 7, 5, 8]
0.0
0.0
[2, 0, 3, 1, 4, 6, 7, 5, 8]
0.0
[2, 4, 3, 1, 0, 6, 7, 5, 8]
0.0
0.0
[2, 4, 3, 1, 5, 6, 7, 0, 8]
0.0010001659393310547
0.0010001659393310547
[2, 4, 3, 1, 5, 6, 0, 7, 8]
0.0010001659393310547
[2, 4, 3, 0, 5, 6, 1, 7, 8]
0.0010001659393310547
[0, 4, 3, 2, 5, 6, 1, 7, 8]
0.0010001659393310547
0.0010001659393310547
[4, 0, 3, 2, 5, 6, 1, 7, 8]
0.0010001659393310547
[4, 5, 3, 2, 0, 6, 1, 7, 8]
0.0010001659393310547
0.0010001659393310547
[4, 5, 3, 2, 7, 6, 1, 0, 8]
0.0010001659393310547
0.0010001659393310547
[4, 5, 3, 2, 7, 6, 0, 1, 8]
0.0010001659393310547
[4, 5, 3, 0, 7, 6, 2, 1, 8]
0.0010001659393310547
[0, 5, 3, 4, 7, 6, 2, 1, 8]
0.0010001659393310547
0.0010001659393310547
[5, 0, 3, 4, 7, 6, 2, 1, 8]
0.0010001659393310547
[5, 7, 3, 4, 0, 6, 2, 1, 8]
0.0010001659393310547
0.0010001659393310547
[5, 7, 3, 4, 1, 6, 2, 0, 8]
0.0010001659393310547
0.0010001659393310547
[5, 7, 3, 4, 1, 6, 0, 2, 8]
0.0010001659393310547
[5, 7,

NameError: name 'elapsed_time' is not defined

In [36]:
#BFS
import numpy as np

class node:
    def __init__(self, start_state):
        self.matrix = start_state
        self.children_list = []

    def get_children_list(self):
        return self.children_list

    def get_node(self):
        return self.matrix

    def add_childrens(self, childrens):
        self.children_list = childrens

    def generate_children_nodes(self):
        child_node = []
        empty_cell = 0
        empty_cell_row = empty_cell_column = 0
        temp_array = None

        for i, array in enumerate(self.matrix):
            if empty_cell in array:
                temp_array = array
                empty_cell_row = i
                break

        for i, value in enumerate(temp_array):
            if value == empty_cell:
                empty_cell_column = i

        left = (empty_cell_row - 1, empty_cell_column)
        right = (empty_cell_row + 1, empty_cell_column)
        up = (empty_cell_row, empty_cell_column + 1)
        bottom = (empty_cell_row, empty_cell_column - 1)

        max_bound = 3

        for direction in [left, right, up, bottom]:
            row, column = direction

            if row >= 0 and row < max_bound and column >= 0 and column < max_bound:
                child_node = self.matrix.copy()
                child_node[empty_cell_row][empty_cell_column] = child_node[row][column]
                child_node[row][column] = empty_cell
                self.children_list.append(node(child_node))

def check_node_list(matrix, mat_list):
    for mat in mat_list:
        if np.array_equal(matrix, mat):

            return False

    return True


def bfs(start_state, goal_state):
    queue = [start_state]
    path = {start_state : None}
    level = {start_state : 0}
    all_nodes = [start_state.get_node()]
    i = 1

    while queue:
        next_queue = []

        for parent_node in queue:
            if np.array_equal(parent_node.get_node(), goal_state.get_node()):
                print("Goal State Reached")
                return (path, parent_node)
            parent_node.generate_children_nodes()
            for child in parent_node.get_children_list():
                if check_node_list(child.get_node(), all_nodes):
                    all_nodes.append(child.get_node())
                    next_queue.append(child)
                    level[child] = i
                    path[child] = parent_node.get_node()
        queue = next_queue
        print(f"Number of Nodes at level {i}: {len(queue)}")
        i += 1
    return (path, parent_node.get_node())

if __name__ == "__main__":
    start_state = node(np.array([[1,2,3],[0,4,6],[7,5,8]]))
    goal_state = node(np.array([[1,2,3],[4,5,6],[7,8,0]]))
    path, parent_node = bfs(start_state, goal_state)
    print("Start State")
    print(start_state.get_node())
    print("Goal State")
    print(goal_state.get_node())

Number of Nodes at level 1: 3
Number of Nodes at level 2: 5
Number of Nodes at level 3: 10
Goal State Reached
Start State
[[1 2 3]
 [0 4 6]
 [7 5 8]]
Goal State
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [33]:
class Node:
    def __init__(self,data,level,fval):
        self.data = data
        self.level = level
        self.fval = fval

    def generate_child(self):
        x,y = self.find(self.data,'0')
        val_list = [[x,y-1],[x,y+1],[x-1,y],[x+1,y]]
        children = []
        for i in val_list:
            child = self.shuffle(self.data,x,y,i[0],i[1])
            if child is not None:
                child_node = Node(child,self.level+1,0)
                children.append(child_node)
        return children
        
    def shuffle(self,puz,x1,y1,x2,y2):
        if x2 >= 0 and x2 < len(self.data) and y2 >= 0 and y2 < len(self.data):
            temp_puz = []
            temp_puz = self.copy(puz)
            temp = temp_puz[x2][y2]
            temp_puz[x2][y2] = temp_puz[x1][y1]
            temp_puz[x1][y1] = temp
            return temp_puz
        else:
            return None
            

    def copy(self,root):
        temp = []
        for i in root:
            t = []
            for j in i:
                t.append(j)
            temp.append(t)
        return temp    
            
    def find(self,puz,x):
        for i in range(0,len(self.data)):
            for j in range(0,len(self.data)):
                if puz[i][j] == x:
                    return i,j


class Puzzle:
    def __init__(self,size):
        self.n = size
        self.open = []
        self.closed = []

    def accept(self):
        puz = []
        for i in range(0,self.n):
            temp = input().split(",")
            puz.append(temp)
        return puz

    def f(self,start,goal):
        return self.h(start.data,goal)+start.level

    def h(self,start,goal):
        temp = 0
        for i in range(0,self.n):
            for j in range(0,self.n):
                if start[i][j] != goal[i][j] and start[i][j] != '0':
                    temp += 1
        return temp
        

    def process(self):
        
        start = [['1', '2', '3'], ['0', '4', '6'], ['7', '5', '8']]         
        goal = [['1', '2', '3'], ['4', '5', '6'], ['7', '8', '0']] 
        print(f"Initial State: {start}")
        start = Node(start,0,0)
        start.fval = self.f(start,goal)
        self.open.append(start)

        while True:
            cur = self.open[0]
            print("\n Next Move \n")
            for i in cur.data:
                for j in i:
                    print(j,end=" ")
                print("")
            if(self.h(cur.data,goal) == 0):
                break
            for i in cur.generate_child():
                i.fval = self.f(i,goal)
                self.open.append(i)
            self.closed.append(cur)
            del self.open[0]
            self.open.sort(key = lambda x:x.fval,reverse=False)

if __name__ == "__main__":
    puz = Puzzle(3)
    puz.process()

Initial State: [['1', '2', '3'], ['0', '4', '6'], ['7', '5', '8']]

 Next Move 

1 2 3 
0 4 6 
7 5 8 

 Next Move 

1 2 3 
4 0 6 
7 5 8 

 Next Move 

1 2 3 
4 5 6 
7 0 8 

 Next Move 

1 2 3 
4 5 6 
7 8 0 
